### ISSUE TITLE
Windows get stuck on top when closing the program without manually untoggling the status

### ISSUE THREAD

**Issue by Fransiscu** [flashwave/topmostfriend#1]
Been using this tool for a little over a week now and encountered this problem

What happens:

Whenever I close the tool, any window that was previously pinned on top stays that way and there is no way to un pin it.

Expected behavior:

Any pinned window should reset its status before closing the program

**Comment by flashwave** [comment]
I'll be releasing version 1.6 within the next week and it will incorporate this feature as something you can enable in the settings.
Unfortunately it won't be using the code in your pull request as it also affects windows that top most friend has not touched, I'll still be crediting you for the idea in the changelog.
